# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

commands:
  echo:
    description: "echoするよ"
    parameters:
      message:
        type: string
        default: "default!"
    steps:
      - run: echo <<parameters.message>>

jobs:
  echo-stg:
    docker:
      - image: "cimg/base:stable"
    steps:
      - echo:
          message: "staging!"

  deploy-stg:
    docker:
      - image: "cimg/base:stable"
    steps:
      - echo:
          message: "deploy staging!"

  echo-prod:
    docker:
      - image: "cimg/base:stable"
    steps:
      - echo:
          message: "production!"

# Orchestrate or schedule a set of jobs
workflows:
  version: 2

  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run

  stg:
    jobs:
      - echo-stg:
          filters:
            branches:
              #only: develop
              # ignore: /.*/ # deploy-stgが動かないのを確認
      - deploy-stg:
          requires:
            - echo-stg
      - echo:
          requires:
            - deploy-stg
          message: "workflowの方でも使えるか試す"

  prod:
    jobs:
      - echo-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
