# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  check-tag:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: echo 'check-tag!'

  check-branch:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: echo 'check-branch!'

  echo-stg:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: echo 'staging!'

  echo-prod:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: echo 'production!'

# Orchestrate or schedule a set of jobs
workflows:
  version: 2

  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run

  stg:
    jobs:
      - echo-stg:
          filters:
            branches:
              only: develop

  prod:
    jobs:
      - check-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      - check-branch:
          requires:
            - check-tag
          filters:
            branches:
              only: master
      - echo-prod:
          requires:
            - check-branch
